### ISSUE TITLE
weird visual issue with phantom wood

### ISSUE THREAD

**Issue by Zack7292** [EndersMagic/EnderMagic#54]
so, i've found a phantom wood, and when i jump while watching down around it, i see a weird blue grass. it doesn't seem to do it with the other phantom woods around this one and it's really weird, if you wait a bit ima give you my world, and my pack after you see the coordonates one the video.

here's the video: https://youtu.be/HvNyPnqg-r8

**Comment by Zack7292** [comment]
modpack link: https://www.mediafire.com/file/vv3qyj52zm7cpz9/InfEx_Test-Test_versinon_V.0.0.007.zip/file

world link: https://www.mediafire.com/file/u5rlao83pbmlktp/New_World-.zip/file

**Comment by hohserg1** [comment]
Fixed!
https://github.com/EndersMagic/EnderMagic/commit/06086490f6985c6eda638760f496abe62c009684
https://www.curseforge.com/minecraft/mc-mods/enders-magic/files/2934582
